### ISSUE TITLE
Models folder empty?

### ISSUE THREAD

**Issue by terhechte** [innovatorved/whisper.api#10]
Hey! Awesome project. The Readme says:

> Here are the available models:
> 
> tiny.en
> tiny.en.q5
> base.en.q5

But the `models` folder is empty. Are these the same models as provided by whisper.cpp? I'm asking because the readme says `Uses a finetuned Whisper model for accurate speech recognition` and I'd love to try that out.

**Comment by innovatorved** [comment]
The model automatically downloads when you start the project. More models will be coming in a couple of weeks.
